import { Limelight, DM_Serif_Display } from "next/font/google";
import "./globals.css";

const limelight = Limelight({
  subsets: ["latin"],
  weight: "400", // Limelight only has 400
  variable: "--font-limelight",
});

const dmSerifDisplay = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400", // Only one weight available
  variable: "--font-dm-serif-display",
});

export const metadata = {
  title: "Interactive Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${limelight.variable} ${dmSerifDisplay.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
